export const OCCUPANCY_START_HOUR = 8;
export const OCCUPANCY_END_HOUR = 18;
export const OCCUPANCY_SLOT_MINUTES = 15;
export const OCCUPANCY_SLOT_HEIGHT_PX = 14;

export const OCCUPANCY_TOTAL_MINUTES =
  (OCCUPANCY_END_HOUR - OCCUPANCY_START_HOUR) * 60;

export const OCCUPANCY_TOTAL_SLOTS =
  OCCUPANCY_TOTAL_MINUTES / OCCUPANCY_SLOT_MINUTES;

export const OCCUPANCY_GRID_HEIGHT_PX =
  OCCUPANCY_TOTAL_SLOTS * OCCUPANCY_SLOT_HEIGHT_PX;
