import {
  CalendarDays,
  ClipboardCheck,
  LayoutDashboard,
  ListOrdered,
  ScanLine,
  Users,
} from "lucide-react";

export const APP_MODULES = [
  {
    id: "overview",
    label: "Visão geral",
    icon: LayoutDashboard,
    description: "Resumo do sistema e atalhos de trabalho.",
    route: "/",
    showInSidebar: true,
    showInQuickAccess: false,
    enabled: true,
    requiredRoles: ["admin", "therapist"],
    order: 0,
  },
  {
    id: "patients",
    label: "Pacientes",
    icon: Users,
    description: "Cadastre, pesquise e mantenha pacientes ativos.",
    route: "/patients",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: true,
    requiredRoles: ["admin"],
    order: 1,
  },
  {
    id: "agenda",
    label: "Agenda",
    icon: CalendarDays,
    description: "Visualize atendimentos diários e semanais por profissional.",
    route: "/agenda",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: false,
    requiredRoles: ["admin", "therapist"],
    order: 2,
  },
  {
    id: "attendance",
    label: "Presença",
    icon: ClipboardCheck,
    description: "Registre presença, faltas e justificativas.",
    route: "/attendance",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: false,
    requiredRoles: ["admin"],
    order: 3,
  },
  {
    id: "checkin",
    label: "Check-in",
    icon: ScanLine,
    description: "Acompanhe chegadas em tempo real na recepção.",
    route: "/check-in",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: false,
    requiredRoles: ["admin", "therapist"],
    order: 4,
  },
  {
    id: "waitlist",
    label: "Fila de espera",
    icon: ListOrdered,
    description: "Gerencie prioridades e histórico de contato.",
    route: "/waitlist",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: false,
    requiredRoles: ["admin"],
    order: 5,
  },
];
