import {
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  LayoutDashboard,
  LayoutGrid,
  ListOrdered,
  MapPin,
  ScanLine,
  ShoppingCart,
  Users,
} from "lucide-react";

export const APP_MODULES = [
  {
    id: "overview",
    label: "Visão geral",
    icon: LayoutDashboard,
    description: "Resumo do sistema e atalhos de trabalho.",
    route: "/",
    showInSidebar: true,
    showInQuickAccess: false,
    enabled: true,
    requiredRoles: ["ADMINISTRADOR", "TECNICO", "RECEPCAO"],
    order: 0,
  },
  {
    id: "patients",
    label: "Pacientes",
    icon: Users,
    description: "Cadastre, pesquise e mantenha pacientes ativos.",
    route: "/patients",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: true,
    requiredRoles: ["ADMINISTRADOR"],
    order: 1,
  },
  {
    id: "protocols",
    label: "Protocolos",
    icon: ClipboardList,
    description: "Abra solicitações administrativas e acompanhe o status dos pedidos.",
    route: "/protocols",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: true,
    requiredRoles: ["ADMINISTRADOR", "RECEPCAO"],
    order: 1.5,
  },
  {
    id: "vendas",
    label: "Vendas",
    icon: ShoppingCart,
    description: "PDV de cantina e eventos, produtos e fiados.",
    route: "/vendas",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: true,
    requiredRoles: ["ADMINISTRADOR"],
    order: 1.6,
  },
  {
    id: "agenda",
    label: "Agenda",
    icon: CalendarDays,
    description: "Visualize atendimentos diários e semanais por profissional.",
    route: "/agenda",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: true,
    requiredRoles: ["ADMINISTRADOR", "TECNICO", "RECEPCAO"],
    order: 2,
  },
  {
    id: "patient-locator",
    label: "Localizar atendido",
    icon: MapPin,
    description: "Encontre rapidamente a sala e o profissional de uma criança no dia.",
    route: "/agenda/localizar-atendido",
    showInSidebar: true,
    showInQuickAccess: true,
    enabled: true,
    requiredRoles: ["ADMINISTRADOR", "RECEPCAO"],
    order: 2.2,
  },
  {
    id: "room-occupancy",
    label: "Ocupação das salas",
    icon: LayoutGrid,
    description: "Consulte horários ocupados e livres por sala na semana.",
    route: "/salas/ocupacao",
    showInSidebar: true,
    showInQuickAccess: false,
    enabled: true,
    requiredRoles: ["ADMINISTRADOR"],
    order: 2.5,
  },
  {
    id: "attendance",
    label: "Presença",
    icon: ClipboardCheck,
    description: "Registre presença, faltas e justificativas.",
    route: "/attendance",
    showInSidebar: false,
    showInQuickAccess: false,
    enabled: false,
    requiredRoles: ["ADMINISTRADOR"],
    order: 3,
  },
  {
    id: "checkin",
    label: "Check-in",
    icon: ScanLine,
    description: "Acompanhe chegadas em tempo real na recepção.",
    route: "/check-in",
    showInSidebar: false,
    showInQuickAccess: false,
    enabled: false,
    requiredRoles: ["ADMINISTRADOR", "TECNICO"],
    order: 4,
  },
  {
    id: "waitlist",
    label: "Fila de espera",
    icon: ListOrdered,
    description: "Gerencie prioridades e histórico de contato.",
    route: "/waitlist",
    showInSidebar: false,
    showInQuickAccess: false,
    enabled: false,
    requiredRoles: ["ADMINISTRADOR"],
    order: 5,
  },
];
